openapi: 3.0.0
info:
  title: Ops Risk Demo
  description: >-
    Demonstration for finding the density of the loss distribution for
    Operational Risk
  version: '1'
servers:
  - url: 'https://e43exqgwxl.execute-api.us-east-1.amazonaws.com/prd'
    description: Production server
paths:
  /v1/ops/density:
    post:
      summary: Computes the loss density for operational risk
      description: Computes the loss density for operational risk
      responses:
        '200':
          description: Density at points
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    density:
                      type: number
                    at_point:
                      type: number
                  required:
                    - density
                    - at_point
                  additionalProperties: false
              example:
                - density: 5
                  at_point: 0
                - density: 3
                  at_point: 1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema:
                type: object
                properties:
                  err:
                    type: string
                required:
                  - err
                additionalProperties: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                t:
                  type: number
                  example: 1
                  description: Time Horizon
                a:
                  type: number
                  example: 0.3
                  description: Speed
                sigma:
                  type: number
                  example: 0.3
                  description: Volatility
                lambda:
                  type: number
                  example: 100
                  description: Jump Frequency
                correlation:
                  type: number
                  example: 0.8
                  description: Correlation
                alpha:
                  type: number
                  example: 1.1
                  description: Alpha
                mu:
                  type: number
                  example: 1300
                  description: Shift (Stable)
                c:
                  type: number
                  example: 100
                  description: Scale (Stable)
                numU:
                  type: integer
                  example: 128
                  description: Steps in U
                numOde:
                  type: integer
                  example: 128
                  description: Steps in ODE
              required:
                - t
                - v0
                - numU
                - numOde
                - a
                - sigma
                - lambda
                - correlation
                - alpha
                - mu
                - c
              type: object
